# Generated by Django 4.2.5 on 2023-10-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('foodgroup', models.ManyToManyField(related_name='ingredients_in_foodgroup', to='foodgroups.foodgroup')),
            ],
        ),
    ]
