# Generated by Django 4.2.6 on 2023-10-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('foodgroups', '0003_remove_foodgroup_ingredients'),
        ('ingredients', '0002_remove_ingredient_foodgroup_ingredient_foodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='users.user'),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='foodgroup',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='foodgroup',
            field=models.ManyToManyField(null=True, related_name='ingredients_in_foodgroup', to='foodgroups.foodgroup'),
        ),
    ]
