# Generated by Django 4.2.6 on 2023-10-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgroups', '0003_remove_foodgroup_ingredients'),
        ('ingredients', '0003_ingredient_user_remove_ingredient_foodgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='foodgroup',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='foodgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients_in_foodgroup', to='foodgroups.foodgroup'),
        ),
    ]
