# Generated by Django 4.2.6 on 2023-10-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_remove_ingredient_foodgroup_ingredient_foodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='subgroup',
            field=models.CharField(default='', max_length=100),
        ),
    ]
