# Generated by Django 4.2.6 on 2023-10-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_ingredient_subgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='subgroup',
            new_name='subgroups',
        ),
    ]
