# Generated by Django 4.2.6 on 2023-10-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgroups', '0003_remove_subgroup_ingredients'),
        ('ingredients', '0006_rename_subgroup_ingredient_subgroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='subgroups',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='subgroups',
            field=models.ManyToManyField(related_name='ingredients', to='subgroups.subgroup'),
        ),
    ]
