# Generated by Django 4.2.5 on 2023-10-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredient_foodgroup_ingredient_foodgroup'),
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='ingredients.ingredient'),
        ),
    ]
