# Generated by Django 4.2.6 on 2023-10-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgroups', '0005_foodgroup_subgroup'),
        ('ingredients', '0005_ingredient_subgroup'),
        ('subgroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='foodgroup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='foodgroup_subgroups', to='foodgroups.foodgroup'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='ingredients',
            field=models.ManyToManyField(related_name='subgroup_ingredients', to='ingredients.ingredient'),
        ),
    ]
