# Generated by Django 4.2.6 on 2023-10-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgroups', '0002_subgroup_foodgroup_subgroup_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='ingredients',
        ),
    ]
