# Generated by Django 4.2.6 on 2023-10-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgroups', '0003_remove_subgroup_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgroup',
            old_name='name',
            new_name='subgroupname',
        ),
    ]
