# Generated by Django 4.2.5 on 2023-10-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgroups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgroup',
            name='ingredients',
        ),
    ]
