# Generated by Django 4.2.6 on 2023-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_remove_ingredient_foodgroup_ingredient_foodgroup'),
        ('foodgroups', '0003_remove_foodgroup_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgroup',
            name='ingredients',
            field=models.ManyToManyField(related_name='foodgroup_ingredients', to='ingredients.ingredient'),
        ),
    ]
