# Generated by Django 4.2.6 on 2023-10-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgroups', '0001_initial'),
        ('foodgroups', '0004_foodgroup_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgroup',
            name='subgroup',
            field=models.ManyToManyField(related_name='subgroup', to='subgroups.subgroup'),
        ),
    ]
